welcome:
  # Comment to be posted on first time issues
  newIssueWelcomeComment: >
    :tada: Thanks for opening your first issue here! Welcome to the community!

  # Comment to be posted on PRs from first time contributors in your repository
  newPRWelcomeComment: >
    :tada: Thanks for opening this pull request! We really appreciate
    contributors like you! :raised_hands:

  # Comment to be posted on pull requests merged by a first time user
  firstPRMergeComment: >
    :tada: Congrats on getting your first pull request merged! We here at Palo
    Alto Networks are so grateful! :heart:

  # Don't welcome bots, they don't have feelings
  ignoreBots: true

  # Members do have feelings, but this creates clutter and it's not always clear
  # when a customer is creating an issue, so we'll ignore members for now.
  ignoreOrgMembers: true
